[package]
name = "strict-num-extended"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
strict-num-extended-macros = { workspace = true }

[lints]
workspace = true
