name: Code Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: lcov
          version: 1.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview
      - name: Install grcov
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: grcov
      - name: Install cargo-llvm-cov
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-llvm-cov
      - name: Run grcov for proc-macro generator code
        run: |
          cargo clean
          CARGO_INCREMENTAL=0 RUSTFLAGS="-C instrument-coverage" cargo test --no-fail-fast
          grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing --ignore "/*" -o generator.lcov
      - name: Run cargo-llvm-cov for generated code
        run: |
          cargo clean
          cargo llvm-cov --lcov --output-path generated.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./generator.lcov,./generated.lcov # optional
          verbose: true # optional (default = false)
          fail_ci_if_error: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
